P2/hw_project/quotes_toscrape/quotes_toscrape/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotesapp.urls')),
    path('users/', include('users.urls')),
]

P2/hw_project/quotes_toscrape/quotesapp/urls.py
from django.urls import path
from . import views

app_name = 'quotesapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('tag/', views.tag, name='tag'),
    path('quote/', views.quote, name='quote'),
    path('author/', views.author, name='author'),
    path('detail/<int:quote_id>', views.detail, name='detail'),
    path('about_author/<int:author_id>',views.about_author, name='about_author'),
]

P2/hw_project/quotes_toscrape/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
                                          name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
                                           name='password_reset_complete'),
]


P2/hw_project/quotes_toscrape/quotesapp/models.py
from django.db import models

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f'{self.name}'


class Author(models.Model):
    fullname = models.CharField(max_length=50, null=False)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    bio = models.TextField()

    def __str__(self):
        return f'{self.fullname}'


class Quote(models.Model):
    quote = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    tags = models.ManyToManyField(Tag)

P2/hw_project/quotes_toscrape/quotesapp/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField
from .models import Author, Quote, Tag


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']


class QuoteForm(ModelForm):
    quote = CharField(min_length=5, max_length=2000, required=True, widget=TextInput())
    author = ModelChoiceField(queryset=Author.objects.all(), widget=TextInput())

    class Meta:
        model = Quote
        fields = ['quote','author']
        exclude = ['tags']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=100, required=True, widget=TextInput)
    born_date = CharField(max_length=100, required=True, widget=TextInput)
    born_location = CharField(max_length=150, required=True, widget=TextInput)
    bio = CharField(max_length=4000,required=True, widget=TextInput)

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'bio']

P2/hw_project/quotes_toscrape/quotesapp/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .forms import QuoteForm, AuthorForm, TagForm
from .models import Author, Quote, Tag


# Create your views here.
def main(request):
    quotes = Quote.objects.all()
    return render(request, 'quotesapp/index.html', {"quotes": quotes})


def tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotesapp:main")
        else:
            return render(request, "quotesapp/tag.html", {"form": form})

    return render(request, "quotesapp/tag.html", {"form": TagForm()})


def author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotesapp:main")
        else:
            return render(request, "quotesapp/author.html", {"form": form})

    return render(request, "quotesapp/author.html", {"form": AuthorForm()})


def quote(request):
    authors = Author.objects.all()
    tags = Tag.objects.all()


    if request.method == "POST":
        form = QuoteForm(request.POST)

        if form.is_valid():
            new_quote = form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist("tags"))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to="quotesapp:main")
        else:
            return render(request, "quotesapp/quote.html", {"authors": authors, "tags": tags, "form": form})

    return render(request, "quotesapp/quote.html", {"authors": authors, "tags": tags, "form": QuoteForm()})


def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    author = Author.objects.get(id=quote.author_id)

    return render(request, "quotesapp/detail.html", {"quote": quote, "author": author})


def about_author(request, author_id):
    author = Author.objects.get(id=author_id)
    
    return render(request, 'quotesapp/about_author.html', {"author": author})

P2/hw_project/quotes_toscrape/quotesapp/templates/quotesapp/about_author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<div class="container-fluid">
    <p>
        <strong>{{ author.fullname }}</strong>
    </p>
    <p>
        Born date: {{ author.born_date }}
    </p>
    <p>
        Born in: {{ author.born_location }}
    </p>
    <p>
        Biography: {{ author.bio }}
    </p>
</div>

{% endblock %}

P2/hw_project/quotes_toscrape/quotesapp/templates/quotesapp/author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Author fullname:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.fullname }}</span>
        <label>Author born date:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.born_date }}</span>
        <label>Author born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
        <label>Author biography:
            {{form.bio}}
        </label>
        <span>{{ form.errors.bio }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

P2/hw_project/quotes_toscrape/quotesapp/templates/quotesapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Quotes</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>

<body>
    <div class="container">
        <div class="row header-box pt-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    <a href="/signup" class="btn btn-primary">SingUp</a>
                    <a href="/login" class="btn btn-primary">Login</a>
                    <a href="/logout" class="btn btn-primary">Logout</a>
                </p>
            </div>
        </div>


        {% block content %} {% endblock %}

    </div>
</body>

</html>

P2/hw_project/quotes_toscrape/quotesapp/templates/quotesapp/detail.html
{% extends "quotesapp/base.html" %}

{% block content %}
{% load extract_tags %}

<div class="container-fluid">
    <p class="text">{{ quote.quote }}</p>
    <p>by <small class="author">{{ author.fullname }}</small></p>
    <p>Tags: <small> {{ quote.tags|tags }} </small></p>
</div>

{% endblock %}

P2/hw_project/quotes_toscrape/quotesapp/templates/quotesapp/index.html
<!DOCTYPE html>
<html lang="en">

{% load extract_tags %}

<head>
    <meta charset="UTF-8" />
    <div class="row header-box">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
    </div>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>

<body>
    <main>
        <div class="container">
            <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
                {% if user.is_authenticated %}
                <ul>
                    <li><a href="{% url 'quotesapp:author' %}" role="button">Add Author</a></li>
                    <li><a href="{% url 'quotesapp:quote' %}" role="button">Add Quote</a></li>
                    <li><a href="{% url 'quotesapp:tag' %}" role="button">Add Tag</a></li>
                </ul>
                <ul>
                    <li>Welcome <b>{{ user.username }}!</b></li>
                    <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
                </ul>
                {% else %}
                <ul>
                    <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                    <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
                </ul>
                {% endif %}
            </nav>

            {% for quote in quotes %}
            <li style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
                <ul><strong>{{ quote.quote }}</strong></ul>
                <ul>by <em>{{quote.author.fullname}}</em>
                    <a href="about_author/{{quote.author_id}}">(about)</a>
                </ul>
                <ul>tags: {{ quote.tags|tags }}</ul>
            </li>

            {% endfor %}
        </div>
    </main>
</body>


</html>

P2/hw_project/quotes_toscrape/quotesapp/templates/quotesapp/quote.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Enter the quote:
            {{form.quote}}
        </label>
        <span>{{form.error.quote}}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="author" required>
                {% for author in authors %}
                <option value="{{author.id}}">{{ author.fullname }}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

P2/hw_project/quotes_toscrape/quotesapp/templates/quotesapp/tag.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}